### ISSUE TITLE
申请加入邮箱

### ISSUE THREAD

**Issue by guozhaoxi** [chenjiandongx/weekly-email-subscribe#15]
29693847@qq.com

**Comment by shuxp** [comment]
davidxp@vip.126.com

**Comment by fjchen7** [comment]
fjchen7@gmail.com

**Comment by Armour-warrior** [comment]
xiangggbond@gmail.com

**Comment by foolgry** [comment]
981852406@qq.com

**Comment by Armour-warrior** [comment]
我订阅成功了吗？




| |
向晋利
|
|
邮箱：xiangjinli123456@163.com
|

签名由 网易邮箱大师 定制

在2018年11月16日 11:40，Foolgry 写道：

981852406@qq.com

**Comment by chenjiandongx** [comment]
DONE https://github.com/chenjiandongx/weekly-email-subscribe/blob/master/receivers.py

**Comment by White-Lee** [comment]
857701789@qq.com 
感谢

**Comment by qiaozhen9636** [comment]
1191179102@qq.com 感谢大佬

**Comment by jizhidemowang** [comment]
baoguoxiao0538@hotmail.com 感谢大佬

**Comment by chenjiandongx** [comment]
DONE https://github.com/chenjiandongx/weekly-email-subscribe/blob/master/receivers.py

**Comment by caelanyang** [comment]
asdf0210@qq.com , thanks

**Comment by yuanjingsong** [comment]
532473857@qq.com
感谢大佬

**Comment by fangmiao97** [comment]
1816232121@qq.com

**Comment by chenjiandongx** [comment]
DONE https://github.com/chenjiandongx/weekly-email-subscribe/blob/master/receivers.py

**Comment by Stormpass** [comment]
xilanjianzhu@126.com

**Comment by inmatop** [comment]
zlmifan@sina.cn  感谢

**Comment by xiexingchao98** [comment]
xiexingchao98@gmail.com

**Comment by chenjiandongx** [comment]
DONE

**Comment by kang011503** [comment]
kang011503@163.com 大神V5

**Comment by seyvoue** [comment]
neil.googl@gmail.com

**Comment by ukuq** [comment]
ukuq@qq.com

**Comment by syzby** [comment]
好的，huai_f@live.cn

**Comment by Jaydonjin** [comment]
13309011825@163.com, thanks

**Comment by coprizepiyo** [comment]
coprizepiyo@hotmail.com

**Comment by chenjiandongx** [comment]
DONE https://github.com/chenjiandongx/weekly-email-subscribe/blob/master/receivers.py

**Comment by haokaifa** [comment]
1013558203@qq.com
Thank you very much!

**Comment by Neulana** [comment]
fupinyou@gmail.com
thanks！

**Comment by chenjiandongx** [comment]
DONE

**Comment by caozhixin** [comment]
871625249@qq.com
thanks

**Comment by chenjiandongx** [comment]
DONE

**Comment by Mei-jing** [comment]
meijingmobile@gmail.com
Thanks

**Comment by zuoxiaobai** [comment]
guoqzuo@gmail.com 
Thanks

**Comment by chenjiandongx** [comment]
DONE
